### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by nikaro** [assen-totin/android-icecast-player#1]
Hello,

Have you though about publish your app under a free licence and publish it on F-Droid ?
It would be nice :-)

Regards.

**Comment by assen-totin** [comment]
Hi, Nicolas,

Thanks for your email.

Have you though about publish your app under a free licence and publish it

> on F-Droid ?
> It would be nice :-)

This app has been open source since its very beginning in 2012. I see no
problems with having it on F-Droid. Should I do anything special about
this?

Home page: http://www.zavedil.com/software-android-icecast-player
Github repo: https://github.com/assen-totin/android-icecast-player

With my best regards,

Assen

**Comment by nikaro** [comment]
Hi,

Great :-)

I think the only missing thing to comply with [F-Droid's inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy) is to specify under which licence your code is released (GPL, Apache, MIT...).

After that, according to their [How-To](https://f-droid.org/wiki/page/Inclusion_How-To), it seems we only need to ask for a submission in their forum.

**Comment by assen-totin** [comment]
Submission created: https://f-droid.org/forums/topic/icecast-player/

**Comment by nikaro** [comment]
Thank you :smile:
